const titles={dashboard:"Backtest Dashboard",scanner:"SEPA Scanner",backtest:"Backtest",fundamentals:"Fundamental Filter",trades:"Trade Log",compare:"Strategy Comparison",reports:"Reports"};
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function nav(v){document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===v));document.getElementById("page-title").textContent=titles[v]||"Wizard"}
document.querySelectorAll(".nav-item,[data-view]").forEach(b=>b.addEventListener("click",()=>b.dataset.view&&nav(b.dataset.view)));
function table(id,rows){const e=document.getElementById(id);if(!e)return;e.innerHTML=rows.map(r=>"<tr>"+r.map((x,i)=>"<td class='"+(i===0?"symbol":"")+"'>"+(x??"—")+"</td>").join("")+"</tr>").join("")}
function draw(id,values,color="#2d91ff"){const svg=document.getElementById(id);if(!svg||!values.length)return;const w=900,h=300,p=18,min=Math.min(...values),max=Math.max(...values),span=max-min||1;const pts=values.map((v,i)=>p+i*(w-2*p)/(values.length-1)+","+(h-p-(v-min)/span*(h-2*p))).join(" ");svg.innerHTML="<g stroke='#183047'><line x1='0' x2='"+w+"' y1='"+h*.25+"' y2='"+h*.25+"'/><line x1='0' x2='"+w+"' y1='"+h*.5+"' y2='"+h*.5+"'/><line x1='0' x2='"+w+"' y1='"+h*.75+"' y2='"+h*.75+"'/></g><polyline points='"+pts+"' fill='none' stroke='"+color+"' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'/>"}
function heat(){const h=document.getElementById("heatmap");if(!h)return;h.innerHTML="";for(let i=0;i<72;i++){const d=document.createElement("div"),n=Math.sin(i*2.4)*.7+Math.cos(i*.77)*.3;d.className=n>.55?"strong":n>.05?"pos":n<-.55?"bad":n<-.05?"neg":"";h.appendChild(d)}}
function setKpis(s){if(!s)return;const cards=document.querySelectorAll(".kpis article");const vals=[fmt(s.return_pct,"%",2),fmt(s.final_capital,"₹",0),fmt(s.max_drawdown_pct,"%",2),fmt(s.profit_factor,"",2),fmt(s.trades,"",0),fmt(s.win_rate_pct,"%",1)];cards.forEach((c,i)=>{const b=c.querySelector("b");if(b)b.textContent=vals[i]||"—"})}
function fmt(v,prefix="",digits=2){if(v===undefined||v===null||Number.isNaN(Number(v)))return"—";const n=Number(v);return prefix==="₹"?"₹"+n.toLocaleString("en-IN",{maximumFractionDigits:digits}):n.toFixed(digits)+prefix}
function renderCandidates(rows){table("candidate-rows",rows.slice(0,8).map(r=>[r.symbol,fmt(r.close,"₹",2),r.rs_rank?Number(r.rs_rank).toFixed(0):"—",r.volume_ratio?Number(r.volume_ratio).toFixed(2)+"×":"—",r.trend?"PASS":"—",r.setup?"PASS":"—",r.setup?"Candidate":"Watch",r.rs_rank?Number(r.rs_rank).toFixed(0):"—"]));document.getElementById("scanner-rows").innerHTML=rows.map(r=>"<tr><td class='symbol'>"+r.symbol+"</td><td>₹"+Number(r.close).toFixed(2)+"</td><td>"+(r.rs_rank?Number(r.rs_rank).toFixed(0):"—")+"</td><td>"+Number(100-r.near_high_pct).toFixed(1)+"%</td><td>"+(r.volume_ratio?Number(r.volume_ratio).toFixed(2):"—")+"×</td><td><span class='tag "+(r.trend?"green":"")+"'>"+(r.trend?"PASS":"FAIL")+"</span></td><td><span class='tag "+(r.setup?"green":"")+"'>"+(r.setup?"SETUP":"WATCH")+"</span></td><td>"+(r.rs_rank?Number(r.rs_rank).toFixed(0):"—")+"</td></tr>").join("")}
async function api(path,opts){const r=await fetch(path,opts);const j=await r.json();if(!r.ok)throw new Error(j.message||"API error");return j}
async function loadDashboard(){try{const h=await api("/api/health");const status=document.querySelector(".data-status");status.innerHTML=h.data_available?"<i></i> Research data detected":"<i style='background:#ff6573'></i> Research data not loaded";const [s,e,t,c]=await Promise.all([api("/api/summary"),api("/api/equity"),api("/api/trades"),api("/api/candidates")]);if(s.ready)setKpis(s.summary);if(e.ready)draw("equity-chart",e.points.map(x=>Number(x.equity)));if(t.ready)table("trade-rows",t.trades.slice(-20).reverse().map(x=>[x.entry_date,x.exit_date,x.symbol,fmt(x.entry,"₹",2),fmt(x.exit,"₹",2),x.pnl!==undefined?Number(x.pnl).toFixed(0):"—",x.exit_reason||"—"]));if(c.ready)renderCandidates(c.candidates);else toast(c.message||"No scanner data");heat()}catch(err){toast(err.message);heat()}}
document.getElementById("run").onclick=async()=>{toast("Running research engine…");try{const r=await api("/api/backtest",{method:"POST"});if(r.ok){toast("Backtest completed");await loadDashboard()}else toast(r.message||"Backtest failed")}catch(e){toast(e.message)}};
document.getElementById("run2").onclick=()=>document.getElementById("run").click();
document.getElementById("scan").onclick=async()=>{toast("Running latest scan…");try{const r=await api("/api/candidates");if(r.ready){renderCandidates(r.candidates);toast("Scanner refreshed")}}catch(e){toast(e.message)}};
document.getElementById("refresh").onclick=loadDashboard;
document.getElementById("search").oninput=e=>{const q=e.target.value.toUpperCase();document.querySelectorAll("#scanner-rows tr").forEach(r=>r.style.display=r.cells[0].textContent.includes(q)?"":"none")};
loadDashboard();